[package]
name = "jsonata-bench-harness"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonata-rs = "0.3"
serde_json = "1.0"
bumpalo = "3.9"

[[bin]]
name = "jsonata-rs-bench"
path = "jsonata_rs_bench.rs"
